export interface StepDoc {
  n: string;
  label: string;
  system: string;
  what: string;
  why: string;
  rule?: string;
  src?: keyof typeof STEP_SOURCES;
  variant?: "subscribe" | "redeem" | "both" | "alt";
}

export const STEP_SOURCES = {
  hkmaGuideline: {
    label: "HKMA guideline on supervision of licensed stablecoin issuers",
    href: "https://www.hkma.gov.hk/media/eng/doc/key-functions/ifc/stablecoin-issuers/Guideline_on_supervision_of_licensed_stablecoin_issuers_eng.pdf",
  },
  noInterest: { label: "Stablecoins Ordinance overview (Morgan Lewis)", href: "https://www.morganlewis.com/pubs/2025/06/hong-kongs-stablecoins-ordinance-to-take-effect-august-1-an-overview-of-the-regulatory-framework" },
  hsbcnetEntitle: { label: "HSBCnet user entitlement guide", href: "https://www.hsbcnet.com/-/media/HSBCnet/learningcentre/Helptext/attachments/user-guide/ug_sa_entitle.pdf" },
  setr010: { label: "ISO 20022 setr.010 SubscriptionOrder", href: "https://www.iotafinance.com/SWIFT-norme-ISO20022-Message-setr-010-001-Subscription-Order.html" },
  setr004: { label: "ISO 20022 setr.004 RedemptionOrder", href: "https://www.iotafinance.com/en/SWIFT-ISO20022-Message-setr-004-001-Redemption-Order.html" },
  ensemble: { label: "HKMA — EnsembleTX phase of Project Ensemble", href: "https://www.hkma.gov.hk/eng/news-and-media/press-releases/2025/11/20251113-3/" },
  chats: { label: "HKICL — HKD CHATS clearing system", href: "https://www.hkicl.com.hk/eng/our_services/clearing_system_in_hong_kong/real_time_gross_settlement_system/hkd_clearing_system_in_hong_kong.php" },
  tds: { label: "HSBC Tokenised Deposit Service (Hong Kong)", href: "https://www.about.hsbc.com.hk/news-and-media/hsbc-launches-tokenised-deposit-service-for-corporate-cash-management-in-hong-kong" },
  csop: { label: "CSOP tokenised money-market class (HSBC as trustee and registrar)", href: "https://www.prnewswire.com/apac/news-releases/csop-debuts-inaugural-tokenised-money-market-fund-offering-302790000.html" },
} as const;

/** Every step the bank panel runs, in order, with the reason it exists. */
export const steps: StepDoc[] = [
  {
    n: "1",
    label: "Approvals verified",
    system: "Approval rules · HSBCnet portal",
    what: "Checks the order carries every signature the client's own rules demand — the creator plus one or two approvers with the right approval limits — before anything else happens.",
    why: "Nothing is reserved, issued or sent to the fund until the order is fully authorised, so an unauthorised instruction can never reach the market.",
    rule: "HSBCnet's default is that the approver must be a different person from the creator; the client's own administrators set the approval groups, limits and any single-person exception.",
    src: "hsbcnetEntitle",
    variant: "both",
  },
  {
    n: "1a",
    label: "Instruction from treasury system verified",
    system: "API / host-to-host · entitlements",
    what: "For orders from the client's own treasury system: verifies the message signature and client certificate, and records that the order was approved inside the client's own workflow.",
    why: "Large treasuries approve in their own systems and send one authorised instruction. The bank still has to prove the message is genuine and unaltered.",
    rule: "Bank-side control; the demo rejects anything whose signature or certificate fails.",
    variant: "alt",
  },
  {
    n: "2",
    label: "Screening & travel rule",
    system: "Screening & travel rule",
    what: "Screens both parties and the wallets involved against sanctions and financial-crime lists, and attaches originator and beneficiary data to the transfer.",
    why: "A licensed stablecoin only ever moves between identified parties. The client is told an order stopped, never which control stopped it.",
    rule: "Financial-crime obligations and the travel-rule expectations that apply to licensed stablecoin transfers.",
    src: "hkmaGuideline",
    variant: "both",
  },
  {
    n: "3",
    label: "Settlement route chosen",
    system: "HSBC settlement-routing service",
    what: "Picks the settlement money for this order: the HSBC HKD stablecoin where the fund accepts it and issuance is live, otherwise tokenised deposits inside HSBC, or across banks through EnsembleTX; if neither is open, the order queues for the next CHATS window.",
    why: "The client asked to invest, not to choose plumbing. Routing is the bank's job, the choice is recorded on the order, and deposits stand by if the coin is unavailable — including when the issuer pauses issuance after a reserve break or incident.",
    rule: "My design, not an established product. The constraint it works around is real: EnsembleTX settles between banks through RTGS during the pilot, and CHATS runs on business days.",
    src: "ensemble",
    variant: "both",
  },
  {
    n: "4",
    label: "Stablecoin issued to the client's HSBC-held wallet",
    system: "Stablecoin issuance and redemption · reserve management · core banking",
    what: "Debits the client's HKD account, moves the same amount into the segregated reserve pool, and issues the matching stablecoin into a wallet HSBC holds for the client.",
    why: "Coin can only come into existence against cash the bank has actually received, so every stablecoins in circulation is backed.",
    rule: "Reserve assets must fully back the tokens in issue, be segregated from the issuer's own assets and be held by an acceptable custodian.",
    src: "hkmaGuideline",
    variant: "subscribe",
  },
  {
    n: "4a",
    label: "Deposits tokenised",
    system: "Tokenised Deposit Service · core banking",
    what: "The fallback when a fund does not accept the stablecoin: holds the amount from the HKD account as tokenised deposits instead.",
    why: "The client's experience does not change; only the settlement asset does.",
    rule: "HSBC's Tokenised Deposit Service is live for corporates in Hong Kong.",
    src: "tds",
    variant: "alt",
  },
  {
    n: "5",
    label: "Cash set aside for settlement",
    system: "Settlement lock — cash and units move together",
    what: "Sets the cash aside for this order. It is still the client's money, and it cannot be spent elsewhere while the order is live.",
    why: "It removes the gap where a client has paid but holds nothing: the cash is committed but not surrendered until units exist.",
    rule: "Delivery-versus-payment; the same principle as any securities settlement.",
    variant: "subscribe",
  },
  {
    n: "6",
    label: "Order sent to transfer agent",
    system: "Fund order routing",
    what: "Sends the subscription to the fund's transfer agent as an ISO 20022 setr.010 message (setr.004 for a redemption), stating that settlement is delivery-versus-payment in the chosen settlement money.",
    why: "Funds are dealt on standard messaging, not bespoke files. A tokenised class still deals the same way.",
    rule: "ISO 20022 fund-order messages; confirmations come back as setr.012 and setr.006.",
    src: "setr010",
    variant: "both",
  },
  {
    n: "7",
    label: "Order accepted by fund",
    system: "Transfer agent & register",
    what: "The transfer agent checks the investor is on the register, the class is open, the order is inside limits and it arrived before the cut-off, then reserves the units.",
    why: "The fund, not the bank, decides whether it will accept an order. This is where a register or eligibility problem surfaces.",
    rule: "Fund rules, prospectus terms and transfer-agency practice. For the CSOP class this is HSBC's own role.",
    src: "csop",
    variant: "both",
  },
  {
    n: "7a",
    label: "Fund units set aside for settlement",
    system: "Settlement lock — cash and units move together · custodial wallets",
    what: "On redemptions: the units are set aside for the order, so they cannot be sold twice while settlement is pending.",
    why: "The mirror image of locking cash on a subscription — the investor commits the units, but still owns them until the exchange happens.",
    rule: "Delivery-versus-payment.",
    variant: "redeem",
  },
  {
    n: "9b",
    label: "Fund's cash locked",
    system: "Settlement lock — cash and units move together",
    what: "On redemptions: the fund's side of the payment is set aside once the price is known.",
    why: "Both legs must be committed before either moves.",
    rule: "Delivery-versus-payment.",
    variant: "redeem",
  },
  {
    n: "8",
    label: "Waiting for valuation point",
    system: "Fund administration · NAV",
    what: "The order sits in today's dealing until the fund strikes its price. The demo fast-forwards this.",
    why: "The stablecoin removes the funding and settlement gap; it does not change how a fund prices. Claiming instant pricing would be wrong.",
    rule: "Money-market funds price at a valuation point on each dealing day.",
    variant: "both",
  },
  { n: "9", label: "NAV struck", system: "Fund administration · NAV", what: "The price is set and the exact number of units is known.", why: "Only now can the two legs be sized precisely for an atomic exchange.", rule: "Fund administration.", variant: "both" },
  {
    n: "9a",
    label: "Interbank leg via EnsembleTX",
    system: "EnsembleTX",
    what: "On the cross-bank deposit fallback only: HSBC and the fund's bank settle the deposit leg between themselves.",
    why: "Deposits are a claim on one bank, so moving them between banks needs bank-to-bank settlement; the stablecoin does not.",
    rule: "EnsembleTX settles tokenised deposits between participating banks, backed by RTGS during the pilot — business hours today.",
    src: "ensemble",
    variant: "alt",
  },
  {
    n: "10",
    label: "Cash and fund units transfer together (DvP)",
    system: "settlement lock · transfer agent · custodial wallets",
    what: "One transaction moves the cash to the fund and the units to the investor. Either both happen or neither does.",
    why: "This is the point of the whole design: no settlement gap, no principal risk, nothing to unwind by hand.",
    rule: "Delivery-versus-payment, enforced by the ledger rather than by timing.",
    variant: "both",
  },
  {
    n: "10a",
    label: "Stablecoin redeemed and removed from circulation; HKD credited",
    system: "Issuance · reserve management · core banking",
    what: "On redemptions: the stablecoin received from the fund is removed from circulation and the same amount is released from the reserve to the client's HKD account at par.",
    why: "Coin exists only while it is needed. Burning on redemption keeps supply equal to the reserve.",
    rule: "Redemption at par, and the HKMA expects valid redemption requests to be processed within one business day.",
    src: "hkmaGuideline",
    variant: "redeem",
  },
  {
    n: "10b",
    label: "Deposits credited",
    system: "Tokenised Deposit Service · core banking",
    what: "The fallback equivalent on redemptions: proceeds arrive as tokenised deposits and are credited to the HKD account.",
    why: "Same outcome for the client whichever route the router chose.",
    rule: "HSBC's Tokenised Deposit Service.",
    src: "tds",
    variant: "alt",
  },
  {
    n: "11",
    label: "Posting & reserve check",
    system: "Core banking & general ledger · reconciliation and regulatory reporting",
    what: "Posts the accounting entries and re-checks that stablecoins in circulation still equals the reserve pool. The result feeds the issuer's returns to the HKMA.",
    why: "A break between supply and reserve is the most serious thing that can go wrong for an issuer, so it is checked after every movement rather than at day end.",
    rule: "Reserve management, record-keeping and reporting obligations of a licensed issuer.",
    src: "hkmaGuideline",
    variant: "both",
  },
  {
    n: "12",
    label: "Confirmation received",
    system: "Fund order routing · HSBCnet portal · API",
    what: "The transfer agent's confirmation (setr.012 or setr.006) arrives, the contract note is issued in HSBCnet and the client's ERP is notified.",
    why: "The client's books and the fund's register have to agree, without anyone re-keying anything.",
    rule: "ISO 20022 confirmations.",
    src: "setr004",
    variant: "both",
  },
];

export const exceptionSteps: StepDoc[] = [
  {
    n: "R1",
    label: "Escrow released",
    system: "Settlement lock — cash and units move together",
    what: "When the fund cannot accept the order, the cash that was set aside returns to the client's wallet.",
    why: "A rejected order must leave the client exactly as they were.",
    rule: "The set-aside cash only ever goes to the fund in exchange for units, or back to the client.",
    variant: "both",
  },
  {
    n: "R2",
    label: "Stablecoin redeemed and removed from circulation; hold released",
    system: "Issuance · reserve management · core banking",
    what: "The unused stablecoin is removed from circulation and the hold on the HKD account is released, so the money is available again.",
    why: "No stablecoin is left in the client's name after a failed order.",
    rule: "Redemption at par; supply falls back in step with the reserve.",
    src: "hkmaGuideline",
    variant: "both",
  },
  {
    n: "G1",
    label: "Order closed",
    system: "Fund order routing",
    what: "When the fund applies a liquidity gate, the redemption is closed with no units locked and the holding unchanged.",
    why: "A fund can refuse a redemption on a given day; the client must be left exactly as they were and told at once.",
    rule: "Fund liquidity management — gates and limits are the manager's tools, enforced in the flow rather than after it.",
    variant: "redeem",
  },
  {
    n: "G2",
    label: "Client offered next dealing day",
    system: "HSBCnet portal",
    what: "The client is told the order was not accepted today and offered the next dealing day or a smaller amount.",
    why: "Every stopped order ends with a person knowing what happens next.",
    rule: "Client messaging never names the control that stopped an order.",
    variant: "redeem",
  },
  {
    n: "Q1",
    label: "Order queued for next CHATS window",
    system: "HKD CHATS (RTGS)",
    what: "If no digital route is open, the order waits for conventional settlement and nothing is debited meanwhile.",
    why: "It shows the gap the stablecoin closes — and that the client is never left with money in limbo.",
    rule: "HKD CHATS runs on business days.",
    src: "chats",
    variant: "alt",
  },
  {
    n: "Q2",
    label: "Client told expected settlement",
    system: "HSBCnet portal · API",
    what: "The order shows as queued with the expected settlement time, in the portal and to the client's ERP.",
    why: "A delay the client can see and plan around is very different from a payment that has gone quiet.",
    rule: "Client messaging.",
    variant: "alt",
  },
];

export const grounded = [
  ["Reserves", "Coin issued only against cash received, into a segregated reserve pool held by a custodian, reconciled to supply and reported to the HKMA.", "hkmaGuideline"],
  ["Redemption", "At par, and processed within one business day.", "hkmaGuideline"],
  ["No yield on the coin", "Licensed issuers may not pay holders interest — which is why the fund, not the coin, is where cash earns.", "noInterest"],
  ["Identified holders", "Approved-wallet listed wallets, screening, and travel-rule data on transfers.", "hkmaGuideline"],
  ["Client authorisation", "The client configures signature groups, limits and sole control; the bank enforces them.", "hsbcnetEntitle"],
  ["Fund messaging", "ISO 20022 setr.010/012 for subscriptions and setr.004/006 for redemptions.", "setr010"],
  ["Market infrastructure", "EnsembleTX settles tokenised deposits between banks, RTGS-backed in the pilot; HKD CHATS runs business days.", "ensemble"],
  ["HSBC's existing roles", "Tokenised Deposit Service live for corporates; trustee, registrar and tokenisation agent for a tokenised HKD money-market class.", "csop"],
] as const;

export const myDesign = [
  ["The settlement-routing service", "Choosing the stablecoin by default and falling back to tokenised deposits is my proposal, not an announced product."],
  ["Custodial wallets", "HSBC holding the client's keys is a reasonable corporate model, but it is a design choice — a client could self-custody."],
  ["Live settlement tracking", "Real portals show four statuses. The step-by-step view is proposed, and labelled as such in the demo."],
  ["Coin enabled on each fund", "No fund has enabled an HSBC HKD stablecoin. The demo assumes it, and shows the fallback for when it hasn't happened."],
  ["HSBC as a BlackRock distributor", "A demo scenario to show one fund working with two licensed stablecoins."],
  ["Timings and amounts", "Valuation point compressed; yields, cut-offs, NAVs, balances and the issuer totals are illustrative."],
] as const;

export const notModelled = [
  "Client onboarding, due diligence and wallet registration as a journey",
  "Sanctions escalation, case management and financial-crime investigations",
  "Key ceremonies, HSM operations and the security model around issuance",
  "On-chain transaction monitoring and analytics",
  "Reserve liquidity stress testing and the investment policy for reserve assets",
  "Disaster recovery, operational resilience and the 24/7 support model beyond a named rota",
  "Fund-side legal agreements, distribution terms and prospectus changes",
  "Accounting and tax treatment for the client, and how reconciliation breaks are worked",
];

export const glossary: [string, string][] = [
  ["Stablecoin (HSBC HKD stablecoin)", "A regulated digital Hong Kong dollar issued by HSBC under its HKMA licence, held only in approved, identified wallets and backed 1:1 by ring-fenced reserves."],
  ["Tokenised deposits (TDS)", "An ordinary HSBC deposit in token form, so it can move 24/7 inside HSBC. It stays a claim on the bank."],
  ["Issue / redeem", "Creating stablecoin against cash received, and cancelling it when the holder wants cash back. The industry says mint and burn."],
  ["Stablecoins in circulation", "The total issued and not yet redeemed. It must always equal the reserves held."],
  ["Order reference (FND-2609-0001)", "The client's reference for one fund order: FND for a fund order, 2609 for the month it was raised (September 2026), then the sequence number for that day. It stays on the order from the ticket through to settlement, so client, bank and fund all quote the same number."],
  ["Delivery versus payment (DvP)", "Cash and fund units change hands in one step, so neither side can be left short."],
  ["Approved-wallet list", "The register of wallets belonging to identified, checked parties. Only these can hold or receive the stablecoin. Also called an allow-list."],
  ["Valuation point", "The moment each day when a fund sets its price. Orders that day settle at that price."],
  ["Transfer agent", "The firm that keeps the fund's register of who owns units, and issues or cancels them."],
  ["EnsembleTX", "The HKMA's platform for settling tokenised deposits between banks, and for tokenised asset transactions."],
  ["CHATS", "Hong Kong's high-value interbank payment system. It runs on business days."],
  ["ISO 20022 (setr.010 / setr.012 / setr.004 / setr.006)", "The standard electronic messages banks and funds use for orders and confirmations: subscription order, subscription confirmation, redemption order, redemption confirmation."],
  ["Creator and approver", "The person who raises an order and the person who approves it. HSBCnet calls them preparer and authoriser."],
  ["Single-person approval", "A client setting where one person may both raise and approve an order. HSBCnet calls it sole transaction control; the default requires two people."],
  ["Signature groups and limits", "The client's own rules about who may approve what, and up to which amount."],
  ["Order dashboard", "The list of orders with their status, sometimes called a blotter."],
  ["Minimum end-to-end pilot", "The smallest version of the whole flow that actually works start to finish — often called a walking skeleton."],
  ["Small end-to-end release", "A release that delivers one complete journey rather than part of every screen — often called a vertical slice."],
  ["MoSCoW", "Priorities: Must, Should, Could, Won't have."],
  ["Story points (Fibonacci)", "Relative size estimates for work: 1, 2, 3, 5, 8, 13. Not days."],
  ["RACI", "Who is Responsible, Accountable, Consulted and Informed for each activity."],
  ["RAID", "A log of Risks, Assumptions, Issues and Dependencies."],
  ["p95", "The level met 95% of the time — so \"under 5 seconds at p95\" means 95 of 100 orders settle faster than that."],
  ["RPO and RTO", "After a failure: how much data may be lost (recovery point) and how quickly service must return (recovery time). RPO 0 means no lost records."],
  ["HSM", "A tamper-resistant device that stores the keys used to issue stablecoin, so no one person can move them."],
  ["Key ceremony", "The witnessed, scripted process for creating those keys, with several people present and a record kept."],
  ["Idempotent", "Safe to send twice: a repeated instruction does not create a second order."],
  ["Subscribe and redeem", "Buying units directly from a fund, and returning them to the fund for cash — not trading them with another investor."],
  ["Travel rule", "The requirement to carry sender and beneficiary details with a transfer."],
];
